# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05c3b900ee20d20b4e3f7e3fad6644a60ca0fb0f16a6bbb0f602062b5b75ed894d5d55586d8cf686023dfeb88c06ce5ae83b8d6bbcce2c21f0a43c017ee0e658

test:
  secret_key_base: 12f408d92284228335720016b24b043d791a1fffca1bc5dea38263340503b85253497ad6237574ebc54ca29f83a0ad5807cf59b0b0740c88926a1d2593914ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
